# Generated by Django 2.2.1 on 2021-09-09 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stokee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'タグ情報データ', 'verbose_name_plural': 'タグ情報データ'},
        ),
        migrations.AddField(
            model_name='post',
            name='like_num',
            field=models.IntegerField(default=0, verbose_name='いいね'),
        ),
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='アイデア価格'),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=255, null=True, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stokee.Post'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='アイデア投稿者'),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='購入日時')),
                ('purchased_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stokee.Post')),
                ('purchased_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='購入者')),
            ],
            options={
                'verbose_name': 'アイデア購入情報データ',
                'verbose_name_plural': 'アイデア購入情報データ',
            },
        ),
    ]
