# Generated by Django 2.2.1 on 2021-09-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokee', '0003_auto_20210926_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='follower_num',
            field=models.IntegerField(default=0, verbose_name='フォロワー'),
        ),
        migrations.AddField(
            model_name='profile',
            name='following_num',
            field=models.IntegerField(default=0, verbose_name='フォロー'),
        ),
    ]
