# Generated by Django 2.2.1 on 2021-09-27 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stokee', '0004_auto_20210926_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
    ]
