# Generated by Django 2.2.1 on 2021-10-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokee', '0007_auto_20211025_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='follower_num',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='following_num',
        ),
        migrations.AddField(
            model_name='profile',
            name='followees',
            field=models.ManyToManyField(related_name='_profile_followees_+', through='stokee.Relationship', to='stokee.Profile', verbose_name='フォロー中のユーザー'),
        ),
        migrations.AddField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(related_name='_profile_followers_+', through='stokee.Relationship', to='stokee.Profile', verbose_name='フォローされているユーザー'),
        ),
    ]
